apiVersion: v1
kind: Service
metadata:
  name: devops-taller-dev-service
  namespace: jenkins-taller
spec:
  selector:
    app: devops-taller-dev
  ports:
    - protocol: TCP
      port: 3000      
      targetPort: 3000 
      nodePort: 31001  
  type: NodePort
