apiVersion: v1
kind: Service
metadata:
  name: devops-taller-prod-service
  namespace: jenkins
spec:
  selector:
    app: devops-taller-prod
  ports:
    - protocol: TCP
      port: 3000       
      targetPort: 3000 
      nodePort: 25000  
  type: NodePort